import { IItem } from "./getItemIds";
import { skuMapping } from "./sku-code";

export const generateIVTransData = (lineItems, items: IItem[]) => {
  const ivTransData = [];

  lineItems.map((lineItem, index: number) => {
    const ivTransItem = {
      SrNo: `${index + 1}`,
      ItemCode: items.find((item) => item.code === skuMapping[lineItem.sku])
        .code, // get item code from item list
      ItemName: items.find((item) => item.code === skuMapping[lineItem.sku])
        .name, // get item name from item list
      DefaultSalesAc: "",
      DefaultSalesAcName: "",
      ItemId: items.find((item) => item.code === skuMapping[lineItem.sku]).id, // get item id from item list
      Qty: parseFloat(lineItem.quantity), // quantity
      UOMName: "Pcs",
      UOM: "5f3d1ba0-c3ae-41e2-a79b-e67dbdac208f",
      Rate: parseFloat(lineItem.price), // price
      RateAfterTax: 0, // price,
      AmountBeforeDis: parseFloat(lineItem.price), // price,
      Discount: 0,
      DiscountQty: "0",
      DiscountAmount: parseFloat(lineItem.total_discount), // total discount ,
      Discount1Qty: 0,
      Discount1: 0,
      Discount1Amount: 0,
      Discount2Qty: 0,
      Discount2: 0,
      Discount2Amount: 0,
      Discount3Qty: 0,
      Discount3: 0,
      Discount3Amount: 0,
      Discount4Qty: 0,
      Discount4: 0,
      Discount4Amount: 0,
      Discount5Qty: 0,
      Discount5: 0,
      Discount5Amount: 0,
      Amount: parseFloat(lineItem.price) - parseFloat(lineItem.total_discount), // price - total discount,
      ExciseAssessRate: "0.0",
      ExciseAssessValue: "0.0",
      ExciseCalcOnId: "",
      ExciseCalcValue: "0.0",
      MRP: parseFloat(lineItem.price), // price,
      VATAssessRate: "0.0",
      VATAssessValue: "0.0",
      VatCalcOnId: "",
      VatCalcValue: "0.0",
      Tax1Name: "IGST",
      TaxId1: "026ac104-5f05-41c3-85af-f62f3d2a9cdb",
      TaxId1Per: 0,
      Asses1Amount: parseFloat(lineItem.price), // price,
      TaxId1Amount: 0, // TODO: have to calculate the tax amount
      Tax2Name: "",
      TaxId2: "",
      TaxId2Per: 0,
      Asses2Amount: 0,
      TaxId2Amount: 0,
      Tax3Name: "",
      TaxId3: "",
      TaxId3Per: 0,
      Asses3Amount: 0,
      TaxId3Amount: 0,
      Tax4Name: "",
      TaxId4: "",
      TaxId4Per: 0,
      Asses4Amount: 0,
      TaxId4Amount: 0,
      Tax5Name: "",
      TaxId5: "",
      TaxId5Per: 0,
      Asses5Amount: 0,
      TaxId5Amount: 0,
      Tax6Name: "",
      TaxId6: "",
      TaxId6Per: 0,
      Asses6Amount: 0,
      TaxId6Amount: 0,
      AmountAfterTax: parseFloat(lineItem.price), // price
      Description: "",
      SchemeType: "",
      SchemeItemId: "",
    };

    ivTransData.push(ivTransItem);
  });

  return ivTransData;
};

// iv trans sample data
//   {
//     "SrNo": 1,
//     "ItemCode": "ACPS",
//     "ItemName": "AMRUTAM CHAWANPRASH - 200GM",
//     "DefaultSalesAc": "",
//     "DefaultSalesAcName": "",
//     "ItemId": "b9ae1d89-14a7-4820-aba6-09079c27be78",
//     "Qty": 1,
//     "UOMName": "Pcs",
//     "UOM": "5f3d1ba0-c3ae-41e2-a79b-e67dbdac208f",
//     "Rate": 1070.59,
//     "RateAfterTax": 0,
//     "AmountBeforeDis": 1070.59,
//     "Discount": 0,
//     "DiscountQty": "0",
//     "DiscountAmount": 107.06,
//     "Discount1Qty": 0,
//     "Discount1": 0,
//     "Discount1Amount": 0,
//     "Discount2Qty": 0,
//     "Discount2": 10,
//     "Discount2Amount": 107.06,
//     "Discount3Qty": 0,
//     "Discount3": 0,
//     "Discount3Amount": 0,
//     "Discount4Qty": 0,
//     "Discount4": 0,
//     "Discount4Amount": 0,
//     "Discount5Qty": 0,
//     "Discount5": 0,
//     "Discount5Amount": 0,
//     "Amount": 963.53,
//     "ExciseAssessRate": "0.0",
//     "ExciseAssessValue": "0.0",
//     "ExciseCalcOnId": "",
//     "ExciseCalcValue": "0.0",
//     "MRP": "0.0",
//     "VATAssessRate": "0.0",
//     "VATAssessValue": "0.0",
//     "VatCalcOnId": "",
//     "VatCalcValue": "0.0",
//     "Tax1Name": "IGST",
//     "TaxId1": "026ac104-5f05-41c3-85af-f62f3d2a9cdb",
//     "TaxId1Per": 12,
//     "Asses1Amount": 963.53,
//     "TaxId1Amount": 115.62,
//     "Tax2Name": "",
//     "TaxId2": "",
//     "TaxId2Per": 0,
//     "Asses2Amount": 0,
//     "TaxId2Amount": 0,
//     "Tax3Name": "",
//     "TaxId3": "",
//     "TaxId3Per": 0,
//     "Asses3Amount": 0,
//     "TaxId3Amount": 0,
//     "Tax4Name": "",
//     "TaxId4": "",
//     "TaxId4Per": 0,
//     "Asses4Amount": 0,
//     "TaxId4Amount": 0,
//     "Tax5Name": "",
//     "TaxId5": "",
//     "TaxId5Per": 0,
//     "Asses5Amount": 0,
//     "TaxId5Amount": 0,
//     "Tax6Name": "",
//     "TaxId6": "",
//     "TaxId6Per": 0,
//     "Asses6Amount": 0,
//     "TaxId6Amount": 0,
//     "AmountAfterTax": 1079.15,
//     "Description": "",
//     "SchemeType": "",
//     "SchemeItemId": ""
// }
